[Interface]
PrivateKey = EJT6oXRG//I/e2b29TLIZ8osIm9GHbcCXoXikPbOyHw=
Address = 10.116.148.16/24
DNS = 10.116.148.1

[Peer]
PublicKey = q0LR19l8ngGDKFnsvob6iCSmtwXqhA0x32WCBbLRiSk=
PresharedKey = rJKiihp07+4QDtzPOjYv31R0xlh1WDXdwvSy079Fezo=
Endpoint = 76.36.60.185:51820
AllowedIPs = 0.0.0.0/0, ::0/0
