[Interface]
PrivateKey = OG4/nkAXd15PN7QpghDWiTQZ+8UF8BudynSGxB2yBUU=
Address = 10.116.148.15/24
DNS = 10.116.148.1

[Peer]
PublicKey = q0LR19l8ngGDKFnsvob6iCSmtwXqhA0x32WCBbLRiSk=
PresharedKey = B3ZPq3+jww51XMgfiky5biEbVGRRVun/htPTnkxKlHs=
Endpoint = 76.36.60.185:51820
AllowedIPs = 0.0.0.0/0, ::/0
