[Interface]
PrivateKey = wACbe+3qx75IwjNmmUZwerwslPl70G/lyZW+UcgYn1U=
Address = 10.116.148.11/24
DNS = 10.116.148.1

[Peer]
PublicKey = q0LR19l8ngGDKFnsvob6iCSmtwXqhA0x32WCBbLRiSk=
PresharedKey = 3i2EU4If7SrkAybaZ3vy/U7K5XtuL/ogetxJrDbyA6k=
Endpoint = 75.181.37.48:51820
AllowedIPs = 0.0.0.0/0, ::0/0
